### ISSUE TITLE
Make Users Admins

### ISSUE THREAD

**Issue by taylormoineau** [taylormoineau/una-webapp#9]
- In user admin screen, add an Admin column to the table. For each user, there will be a checkbox. Clicking it will immediately change whether or not they are an admin.
- The database will need a new column to store this. Probably just a boolean?

**Comment by taylormoineau** [comment]
There is a conflict with the "make admin" checkboxes in the table. Their state is set based on the "admin" column in the database. But when I try to change the database state by clicking, theres a conflict somewhere along the way. It doesn't want to change from true to false because the database is still true. So it never completes the first task of clicking.

Also for some reason index.js does not want me to add handlers for "editPerson.js". I had to comment them out so it wouldn't just break.

**Comment by andrewmaxwell** [comment]
Can you push your changes so I can have a look?

**Comment by andrewmaxwell** [comment]
Github should automagically move this to done once the PR is merged.
